/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as DashboardTimelineRouteImport } from './routes/dashboard.timeline'
import { Route as DashboardSkillsRouteImport } from './routes/dashboard.skills'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardOutputRouteImport } from './routes/dashboard.output'
import { Route as DashboardExperienceRouteImport } from './routes/dashboard.experience'
import { Route as DashboardEducationRouteImport } from './routes/dashboard.education'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard.discover'
import { Route as DashboardAchievementsRouteImport } from './routes/dashboard.achievements'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'
import { Route as DashboardDiscoverTrackerRouteImport } from './routes/dashboard.discover.tracker'
import { Route as DashboardDiscoverSearchRouteImport } from './routes/dashboard.discover.search'
import { Route as DashboardDiscoverSavedRouteImport } from './routes/dashboard.discover.saved'
import { Route as DashboardDiscoverOpportunityIdRouteImport } from './routes/dashboard.discover.$opportunityId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTimelineRoute = DashboardTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSkillsRoute = DashboardSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutputRoute = DashboardOutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExperienceRoute = DashboardExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEducationRoute = DashboardEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchievementsRoute = DashboardAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardDiscoverTrackerRoute =
  DashboardDiscoverTrackerRouteImport.update({
    id: '/tracker',
    path: '/tracker',
    getParentRoute: () => DashboardDiscoverRoute,
  } as any)
const DashboardDiscoverSearchRoute = DashboardDiscoverSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardDiscoverRoute,
} as any)
const DashboardDiscoverSavedRoute = DashboardDiscoverSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardDiscoverRoute,
} as any)
const DashboardDiscoverOpportunityIdRoute =
  DashboardDiscoverOpportunityIdRouteImport.update({
    id: '/$opportunityId',
    path: '/$opportunityId',
    getParentRoute: () => DashboardDiscoverRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/discover': typeof DashboardDiscoverRouteWithChildren
  '/dashboard/education': typeof DashboardEducationRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/output': typeof DashboardOutputRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/discover/$opportunityId': typeof DashboardDiscoverOpportunityIdRoute
  '/dashboard/discover/saved': typeof DashboardDiscoverSavedRoute
  '/dashboard/discover/search': typeof DashboardDiscoverSearchRoute
  '/dashboard/discover/tracker': typeof DashboardDiscoverTrackerRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/discover': typeof DashboardDiscoverRouteWithChildren
  '/dashboard/education': typeof DashboardEducationRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/output': typeof DashboardOutputRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/discover/$opportunityId': typeof DashboardDiscoverOpportunityIdRoute
  '/dashboard/discover/saved': typeof DashboardDiscoverSavedRoute
  '/dashboard/discover/search': typeof DashboardDiscoverSearchRoute
  '/dashboard/discover/tracker': typeof DashboardDiscoverTrackerRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/discover': typeof DashboardDiscoverRouteWithChildren
  '/dashboard/education': typeof DashboardEducationRoute
  '/dashboard/experience': typeof DashboardExperienceRoute
  '/dashboard/output': typeof DashboardOutputRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/discover/$opportunityId': typeof DashboardDiscoverOpportunityIdRoute
  '/dashboard/discover/saved': typeof DashboardDiscoverSavedRoute
  '/dashboard/discover/search': typeof DashboardDiscoverSearchRoute
  '/dashboard/discover/tracker': typeof DashboardDiscoverTrackerRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/achievements'
    | '/dashboard/discover'
    | '/dashboard/education'
    | '/dashboard/experience'
    | '/dashboard/output'
    | '/dashboard/projects'
    | '/dashboard/skills'
    | '/dashboard/timeline'
    | '/p/$projectId'
    | '/dashboard/'
    | '/dashboard/discover/$opportunityId'
    | '/dashboard/discover/saved'
    | '/dashboard/discover/search'
    | '/dashboard/discover/tracker'
    | '/dashboard/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/achievements'
    | '/dashboard/discover'
    | '/dashboard/education'
    | '/dashboard/experience'
    | '/dashboard/output'
    | '/dashboard/projects'
    | '/dashboard/skills'
    | '/dashboard/timeline'
    | '/p/$projectId'
    | '/dashboard'
    | '/dashboard/discover/$opportunityId'
    | '/dashboard/discover/saved'
    | '/dashboard/discover/search'
    | '/dashboard/discover/tracker'
    | '/dashboard/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/achievements'
    | '/dashboard/discover'
    | '/dashboard/education'
    | '/dashboard/experience'
    | '/dashboard/output'
    | '/dashboard/projects'
    | '/dashboard/skills'
    | '/dashboard/timeline'
    | '/p/$projectId'
    | '/dashboard/'
    | '/dashboard/discover/$opportunityId'
    | '/dashboard/discover/saved'
    | '/dashboard/discover/search'
    | '/dashboard/discover/tracker'
    | '/dashboard/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PProjectIdRoute: typeof PProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/timeline': {
      id: '/dashboard/timeline'
      path: '/timeline'
      fullPath: '/dashboard/timeline'
      preLoaderRoute: typeof DashboardTimelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/skills': {
      id: '/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/output': {
      id: '/dashboard/output'
      path: '/output'
      fullPath: '/dashboard/output'
      preLoaderRoute: typeof DashboardOutputRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/experience': {
      id: '/dashboard/experience'
      path: '/experience'
      fullPath: '/dashboard/experience'
      preLoaderRoute: typeof DashboardExperienceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/education': {
      id: '/dashboard/education'
      path: '/education'
      fullPath: '/dashboard/education'
      preLoaderRoute: typeof DashboardEducationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements': {
      id: '/dashboard/achievements'
      path: '/achievements'
      fullPath: '/dashboard/achievements'
      preLoaderRoute: typeof DashboardAchievementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/discover/tracker': {
      id: '/dashboard/discover/tracker'
      path: '/tracker'
      fullPath: '/dashboard/discover/tracker'
      preLoaderRoute: typeof DashboardDiscoverTrackerRouteImport
      parentRoute: typeof DashboardDiscoverRoute
    }
    '/dashboard/discover/search': {
      id: '/dashboard/discover/search'
      path: '/search'
      fullPath: '/dashboard/discover/search'
      preLoaderRoute: typeof DashboardDiscoverSearchRouteImport
      parentRoute: typeof DashboardDiscoverRoute
    }
    '/dashboard/discover/saved': {
      id: '/dashboard/discover/saved'
      path: '/saved'
      fullPath: '/dashboard/discover/saved'
      preLoaderRoute: typeof DashboardDiscoverSavedRouteImport
      parentRoute: typeof DashboardDiscoverRoute
    }
    '/dashboard/discover/$opportunityId': {
      id: '/dashboard/discover/$opportunityId'
      path: '/$opportunityId'
      fullPath: '/dashboard/discover/$opportunityId'
      preLoaderRoute: typeof DashboardDiscoverOpportunityIdRouteImport
      parentRoute: typeof DashboardDiscoverRoute
    }
  }
}

interface DashboardDiscoverRouteChildren {
  DashboardDiscoverOpportunityIdRoute: typeof DashboardDiscoverOpportunityIdRoute
  DashboardDiscoverSavedRoute: typeof DashboardDiscoverSavedRoute
  DashboardDiscoverSearchRoute: typeof DashboardDiscoverSearchRoute
  DashboardDiscoverTrackerRoute: typeof DashboardDiscoverTrackerRoute
}

const DashboardDiscoverRouteChildren: DashboardDiscoverRouteChildren = {
  DashboardDiscoverOpportunityIdRoute: DashboardDiscoverOpportunityIdRoute,
  DashboardDiscoverSavedRoute: DashboardDiscoverSavedRoute,
  DashboardDiscoverSearchRoute: DashboardDiscoverSearchRoute,
  DashboardDiscoverTrackerRoute: DashboardDiscoverTrackerRoute,
}

const DashboardDiscoverRouteWithChildren =
  DashboardDiscoverRoute._addFileChildren(DashboardDiscoverRouteChildren)

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardRouteChildren {
  DashboardAchievementsRoute: typeof DashboardAchievementsRoute
  DashboardDiscoverRoute: typeof DashboardDiscoverRouteWithChildren
  DashboardEducationRoute: typeof DashboardEducationRoute
  DashboardExperienceRoute: typeof DashboardExperienceRoute
  DashboardOutputRoute: typeof DashboardOutputRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardSkillsRoute: typeof DashboardSkillsRoute
  DashboardTimelineRoute: typeof DashboardTimelineRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAchievementsRoute: DashboardAchievementsRoute,
  DashboardDiscoverRoute: DashboardDiscoverRouteWithChildren,
  DashboardEducationRoute: DashboardEducationRoute,
  DashboardExperienceRoute: DashboardExperienceRoute,
  DashboardOutputRoute: DashboardOutputRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardSkillsRoute: DashboardSkillsRoute,
  DashboardTimelineRoute: DashboardTimelineRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PProjectIdRoute: PProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
