-- ============================================================
-- Brio — Stage 3 Discover: follow-up migration 004
--
-- Two small, additive changes prompted by importing a real dataset
-- (supabase/import-hackathons.sql, generated by scripts/import-hackathons.mjs):
--
-- 1. `career_impact_score` — the PRD names "prestige/career impact" as a
--    primary Metadata-based recommendation signal (PRD §6), but the
--    original migration only modeled prestige categorically
--    (School/Regional/National/International) with nothing for career
--    impact specifically. The imported dataset provides a real 1-10
--    career_impact_score per opportunity, so rather than discard it,
--    it gets a proper column and a place in the scoring function.
-- 2. A unique index on (title, organization) — so re-running an import of
--    the same real catalog (script re-run, or importing an overlapping
--    second dataset later) is naturally idempotent instead of creating
--    duplicate rows. (See the index definition below for why this key was
--    chosen over application_url.)
-- ============================================================

alter table public.opportunities
  add column if not exists career_impact_score smallint;

alter table public.opportunities
  drop constraint if exists opportunities_career_impact_score_check;
alter table public.opportunities
  add constraint opportunities_career_impact_score_check check (
    career_impact_score is null or career_impact_score between 1 and 10
  );

-- Originally this was a uniqueness assumption on `application_url` alone,
-- but real imported data disproved that: it's common for one organizing
-- body to run many genuinely distinct opportunities off a single homepage
-- URL (e.g. one institution's site listing 17 different named olympiad
-- subjects). (title, organization) is a far safer natural key — two
-- distinct real opportunities sharing both an identical title AND an
-- identical organization is vanishingly unlikely, and on the rare
-- occasion the same opportunity appears in more than one imported
-- dataset, that's exactly when merging into one row via ON CONFLICT DO
-- UPDATE is the correct behavior.
create unique index if not exists opportunities_title_org_key
  on public.opportunities (title, organization);

-- Extend the recommendation scorer with the new signal. This is the same
-- function body as migration 003's, with one additive scoring term; every
-- eligibility/exclusion rule is unchanged.
create or replace function public.recommend_opportunities(
  p_user_id uuid,
  p_limit integer default 30
)
returns table (
  opportunity_id uuid,
  score numeric,
  matched_skills text[],
  matched_tags text[],
  is_exploration boolean
)
language plpgsql
set search_path = public
as $$
declare
  v_grade_rank smallint;
  v_location text;
  v_skills_lower text[];
  v_tags_lower text[];
  v_prestige_rank smallint;
  v_explore_limit integer;
begin
  if p_user_id is distinct from auth.uid() then
    raise exception 'not authorized';
  end if;

  select academic_level_rank, nullif(trim(location), '')
  into v_grade_rank, v_location
  from public.profiles where id = p_user_id;

  select coalesce(array_agg(distinct lower(name)), '{}')
  into v_skills_lower
  from public.skills where user_id = p_user_id;

  select coalesce(array_agg(distinct lower(t.name)), '{}')
  into v_tags_lower
  from public.tags t where t.user_id = p_user_id and t.type in ('domain', 'tech');

  select coalesce(max(public.prestige_rank(level)), 1)
  into v_prestige_rank
  from public.achievements where user_id = p_user_id;

  p_limit := greatest(coalesce(p_limit, 30), 1);
  v_explore_limit := greatest(p_limit / 10, 1);

  return query
  with eligible as (
    select o.*
    from public.opportunities o
    where o.is_active = true
      and (o.rolling_deadline = true or o.application_deadline is null or o.application_deadline > now())
      and (o.eligibility_grade_min is null or v_grade_rank is null or o.eligibility_grade_min <= v_grade_rank)
      and (o.eligibility_grade_max is null or v_grade_rank is null or o.eligibility_grade_max >= v_grade_rank)
      and (o.country is null or v_location is null or v_location ilike '%' || o.country || '%')
      and not exists (
        select 1 from public.opportunity_feedback f
        where f.opportunity_id = o.id and f.user_id = p_user_id and f.feedback = 'not_relevant'
      )
      and not exists (
        select 1 from public.applications a
        where a.opportunity_id = o.id and a.user_id = p_user_id
      )
  ),
  matches as (
    select
      e.*,
      array(select rs from unnest(e.required_skills) rs where lower(rs) = any(v_skills_lower)) as m_skills,
      array(select tg from unnest(e.tags) tg where lower(tg) = any(v_tags_lower)) as m_tags
    from eligible e
  ),
  scored as (
    select
      m.id as s_opportunity_id,
      (
        coalesce(array_length(m.m_skills, 1), 0) * 10.0
        + coalesce(array_length(m.m_tags, 1), 0) * 6.0
        + (case when public.prestige_rank(m.prestige_level) <= v_prestige_rank + 1 then 3.0 else 0.0 end)
        + (case
            when m.rolling_deadline or m.application_deadline is null then 0.0
            when m.application_deadline < now() + interval '3 days' then 5.0
            when m.application_deadline < now() + interval '7 days' then 3.5
            when m.application_deadline < now() + interval '14 days' then 2.0
            else 0.0
          end)
        -- New: a modest bonus for opportunities with a strong real-world
        -- career-impact rating (High-Aspirant persona, PRD §2/§6). Scaled
        -- down (÷5) relative to skill/tag matches so it nudges rather
        -- than dominates the ranking.
        + (coalesce(m.career_impact_score, 0)::numeric / 5.0)
        + ln(1 + m.saves_count) * 1.5
        + ln(1 + m.views_count) * 0.5
        + random() * 0.75
      )::numeric as s_score,
      m.m_skills as s_matched_skills,
      m.m_tags as s_matched_tags
    from matches m
  ),
  ranked as (
    select scored.*, row_number() over (order by s_score desc) as rn
    from scored
  ),
  top_picks as (
    select s_opportunity_id, s_score, s_matched_skills, s_matched_tags, false as s_is_exploration
    from ranked
    where rn <= greatest(p_limit - v_explore_limit, 1)
  ),
  exploration as (
    select e.id, 0::numeric, '{}'::text[], '{}'::text[], true
    from eligible e
    where e.id not in (select s_opportunity_id from top_picks)
    order by random()
    limit v_explore_limit
  )
  select * from top_picks
  union all
  select * from exploration;
end;
$$;

grant execute on function public.recommend_opportunities(uuid, integer) to authenticated;
